<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>city_announcement_companies</name>
   <tag></tag>
   <elementGuidId>03eef209-fb9e-4d25-b930-de1850dc4020</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.city-announcement-companies</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
