<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bill</name>
   <tag></tag>
   <elementGuidId>9b30309a-04b4-4974-8509-b9099d971d70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#bill</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
