<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>city_list</name>
   <tag></tag>
   <elementGuidId>95c8f8d4-15b4-4400-8b09-cfcc40f75d56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#city_list</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
