<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>household</name>
   <tag></tag>
   <elementGuidId>bb32afd4-cb4f-48b7-b062-2f8537ca7748</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#household</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
