<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>prefecture_code</name>
   <tag></tag>
   <elementGuidId>acfdf791-db04-4eeb-84c8-eed9aee18412</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prefecture_code</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
