<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>simple_simulation_estimate_btn</name>
   <tag></tag>
   <elementGuidId>dfaf26c7-0b9d-4061-afb7-564d0babb179</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#simple_simulation_estimate_btn</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
