<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>simple_simulation_btn</name>
   <tag></tag>
   <elementGuidId>de396a82-ff63-421a-b298-178db7e17f63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#simple_simulation_btn</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
