<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>simulation_register_form</name>
   <tag></tag>
   <elementGuidId>5a8a7bf2-f953-404b-9ec2-8c3631fbb52b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#simulation_register_form</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
