<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>name</name>
   <tag></tag>
   <elementGuidId>327f4ce5-aa36-4b35-b0ad-b44fe90c1a93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=lpgas_contact\[name\]]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'text' and @name = 'lpgas_contact[name]' and @placeholder = '例） 山田 太郎']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lpgas_contact[name]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>例） 山田 太郎</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register_form&quot;)/div[@class=&quot;form-wrap&quot;]/form[1]/div[@class=&quot;steps-container swiper-container-fade swiper-container-horizontal swiper-container-autoheight&quot;]/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide swiper-slide-active&quot;]/div[@class=&quot;slide-content slide-content-5&quot;]/div[@class=&quot;address-box input-wrap error-wrap contact-wrap&quot;]/div[@class=&quot;field-mail&quot;]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
