<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>number_of_rooms</name>
   <tag></tag>
   <elementGuidId>83aafcbe-6dd1-4a3a-bb7c-91335248b22a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=lpgas_contact\[number_of_rooms\]]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@type = 'tel' and @name = 'lpgas_contact[gas_latest_billing_amount]']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lpgas_contact[gas_latest_billing_amount]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register_form&quot;)/div[@class=&quot;form-wrap&quot;]/form[1]/div[@class=&quot;steps-container swiper-container-fade swiper-container-horizontal swiper-container-autoheight&quot;]/div[@class=&quot;swiper-wrapper&quot;]/div[@class=&quot;swiper-slide swiper-slide-active&quot;]/div[@class=&quot;slide-content slide-content-4&quot;]/div[@class=&quot;address-box input-wrap gas-wrap&quot;]/div[@class=&quot;row-wrap&quot;]/div[@class=&quot;field-bill error-wrap remove-error&quot;]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
