<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>house_hold</name>
   <tag></tag>
   <elementGuidId>133a28be-6e44-4112-a851-5c64422eb352</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#house_hold</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//select[@id = 'lpgas_contact_gas_meter_checked_month' and @name = 'lpgas_contact[gas_meter_checked_month]' and (text() = '
	選択
	1月
	2月
	3月
	4月
	5月
	6月
	7月
	8月
	9月
	10月
	11月
	12月
' or . = '
	選択
	1月
	2月
	3月
	4月
	5月
	6月
	7月
	8月
	9月
	10月
	11月
	12月
')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lpgas_contact_gas_meter_checked_month</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lpgas_contact[gas_meter_checked_month]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
	選択
	1月
	2月
	3月
	4月
	5月
	6月
	7月
	8月
	9月
	10月
	11月
	12月
</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lpgas_contact_gas_meter_checked_month&quot;)</value>
   </webElementProperties>
</WebElementEntity>
