<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>katalon_02</name>
   <tag></tag>
   <elementGuidId>b7af2042-57a3-4b65-9eac-696f12686ef6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#katalon_02</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
