<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>katalon_01</name>
   <tag></tag>
   <elementGuidId>759028f3-db15-478a-bd41-81fe2ade61a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#katalon_01</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
