<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>katalon_04</name>
   <tag></tag>
   <elementGuidId>20f5179b-f91a-4585-a424-8c5f5fbef5fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#katalon_04</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
