<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>katalon_03</name>
   <tag></tag>
   <elementGuidId>47cac6d0-33e6-41dd-b8da-2964556a9d0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#katalon_03</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
