<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>house_kind</name>
   <tag></tag>
   <elementGuidId>80b7897a-f6a7-41e9-ad3c-a4aeddffbbea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#house_kind</value>
      </entry>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
