<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>enquire_suggest</name>
   <tag></tag>
   <elementGuidId>2330fa9a-a70b-4a3d-9ae8-ceb27eb53464</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = '
    お困りの方はこちら
  ' or . = '
    お困りの方はこちら
  ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#match_modal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>contract-body</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    お困りの方はこちら
  </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;estimate match-form-old&quot;]/div[@class=&quot;match-screen-notice-pc match-screen-enquire-notice match-screen-notice-show&quot;]/div[@class=&quot;contract-body&quot;]</value>
   </webElementProperties>
</WebElementEntity>
