<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alert_success</name>
   <tag></tag>
   <elementGuidId>ab543736-67de-4af7-a7b2-5f2854b0e7e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.alert.alert-success</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
