<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>katalon_03_auto</name>
   <tag></tag>
   <elementGuidId>d1715ca3-2d30-47a2-994a-b80aa9122696</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=conversion_id]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
