<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>page_pin</name>
   <tag></tag>
   <elementGuidId>c0a8e886-55e8-49e1-a1cf-09c74935b424</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=pin]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
